name: Release

on:
  push:
    branches: [main]

jobs:
  Release:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set DATE
        id: set-date
        run: |
          DATE=`TZ=Asia/Tokyo date "+%Y-%m-%dT%H%M"`
          echo "::set-output name=DATE::$DATE"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.set-date.outputs.DATE }}
          release_name: ${{ steps.set-date.outputs.DATE }}
